<!-- Signature Modal -->
<div id="signatureModal" class="fixed inset-0 bg-gray-800 bg-opacity-75 flex items-center justify-center z-50 hidden">
    <div class="bg-white rounded-lg shadow-2xl w-full max-w-2xl transform transition-all">
        <div class="px-6 py-4 border-b border-gray-200 flex justify-between items-center">
            <h3 class="text-lg font-semibold text-gray-800">Create Signature</h3>
            <button id="closeSignatureModal" class="p-1 text-gray-500 hover:text-gray-700">&times;</button>
        </div>
        
        <div class="p-6">
            <!-- Tabs -->
            <div class="border-b border-gray-200 mb-4">
                <nav class="-mb-px flex space-x-6" aria-label="Tabs">
                    <button class="signature-tab active-tab" data-tab="draw">Draw</button>
                    <button class="signature-tab" data-tab="type">Type</button>
                    <button class="signature-tab" data-tab="upload">Upload</button>
                </nav>
            </div>
            
            <!-- Tab Content -->
            <div id="signatureTabContent">
                <!-- Draw Tab -->
                <div id="drawTab" class="signature-tab-pane active">
                    <canvas id="signatureCanvas" class="border border-gray-300 rounded-md w-full" width="550" height="200"></canvas>
                    <div class="mt-2 text-right">
                        <button id="clearSignatureCanvas" class="text-sm text-blue-600 hover:underline">Clear</button>
                    </div>
                </div>
                
                <!-- Type Tab -->
                <div id="typeTab" class="signature-tab-pane hidden">
                    <input type="text" id="signatureTextInput" class="w-full px-3 py-2 border border-gray-300 rounded-md" placeholder="Type your name">
                    <div class="mt-4">
                        <label class="block text-sm font-medium text-gray-700 mb-2">Select Style</label>
                        <div class="grid grid-cols-2 gap-4" id="signatureFontOptions">
                            <!-- Font options will be generated by JS -->
                        </div>
                    </div>
                </div>
                
                <!-- Upload Tab -->
                <div id="uploadTab" class="signature-tab-pane hidden">
                    <div id="signatureUploadDropzone" class="border-2 border-dashed border-gray-300 rounded-md p-8 text-center cursor-pointer hover:border-blue-500">
                        <p class="text-gray-500">Drag & drop an image here, or click to select a file</p>
                        <input type="file" id="signatureUploadInput" class="hidden" accept="image/*">
                    </div>
                    <div id="signaturePreviewContainer" class="mt-4 hidden">
                        <img id="signatureImagePreview" class="max-w-xs mx-auto" />
                    </div>
                </div>
            </div>
        </div>

        <div class="px-6 py-4 bg-gray-50 border-t border-gray-200 text-right">
            <button id="applySignatureBtn" class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">Apply Signature</button>
        </div>
    </div>
</div>

<style>
.signature-tab {
    padding: 0.5rem 1rem;
    border: none;
    background: none;
    cursor: pointer;
    font-weight: 500;
    color: #6b7280;
    border-bottom: 2px solid transparent;
}
.signature-tab.active-tab {
    color: #3b82f6;
    border-bottom-color: #3b82f6;
}
.signature-font-preview {
    padding: 1rem;
    border: 1px solid #d1d5db;
    border-radius: 0.375rem;
    cursor: pointer;
    font-size: 1.5rem;
    text-align: center;
}
.signature-font-preview.selected {
    border-color: #3b82f6;
    box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.5);
}
</style> 