<div class="flex-1 bg-gray-100 overflow-hidden relative">
    <!-- Canvas Container -->
    <div class="h-full overflow-auto custom-scrollbar" id="canvasContainer">
        <!-- Canvas Controls -->
        <div class="flex items-center justify-center pt-4 pb-2">
            <div class="flex items-center space-x-3 bg-white rounded-lg shadow-sm border border-gray-200 px-4 py-2">
                <!-- Device Preview Selector -->
                <div class="flex items-center space-x-2">
                    <label class="text-xs font-medium text-gray-600">Preview:</label>
                    <select id="deviceSelector" class="text-xs border-none bg-transparent focus:ring-0 cursor-pointer">
                        <option value="desktop">Desktop</option>
                        <option value="tablet">Tablet</option>
                        <option value="mobile">Mobile</option>
                        <option value="email">Email Client</option>
                    </select>
                </div>
                
                <!-- Zoom Controls -->
                <div class="flex items-center space-x-2 border-l border-gray-200 pl-3">
                    <button id="zoomOut" class="p-1 text-gray-500 hover:text-gray-700">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM13 10H7"></path>
                        </svg>
                    </button>
                    <span id="zoomLevel" class="text-xs font-medium text-gray-600 w-12 text-center">100%</span>
                    <button id="zoomIn" class="p-1 text-gray-500 hover:text-gray-700">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM10 7v3m0 0v3m0-3h3m-3 0H7"></path>
                        </svg>
                    </button>
                </div>
                
                <!-- Grid Toggle -->
                <div class="flex items-center space-x-2 border-l border-gray-200 pl-3">
                    <label class="flex items-center cursor-pointer">
                        <input type="checkbox" id="gridToggle" checked class="sr-only">
                        <div class="relative">
                            <div class="block bg-gray-600 w-8 h-4 rounded-full"></div>
                            <div class="dot absolute left-1 top-0.5 bg-white w-3 h-3 rounded-full transition"></div>
                        </div>
                        <span class="ml-2 text-xs font-medium text-gray-600">Grid</span>
                    </label>
                </div>
                
                <!-- Rulers Toggle -->
                <div class="flex items-center space-x-2">
                    <label class="flex items-center cursor-pointer">
                        <input type="checkbox" id="rulersToggle" class="sr-only">
                        <div class="relative">
                            <div class="block bg-gray-300 w-8 h-4 rounded-full"></div>
                            <div class="dot absolute left-1 top-0.5 bg-white w-3 h-3 rounded-full transition"></div>
                        </div>
                        <span class="ml-2 text-xs font-medium text-gray-600">Rulers</span>
                    </label>
                </div>
            </div>
        </div>
        
        <!-- Canvas Area -->
        <div class="flex justify-center px-4 pb-8">
            <div class="relative">
                <!-- Rulers -->
                <div id="horizontalRuler" class="hidden absolute -top-6 left-0 right-0 h-6 bg-white border-b border-gray-300 text-xs text-gray-500">
                    <!-- Ruler marks will be generated by JavaScript -->
                </div>
                <div id="verticalRuler" class="hidden absolute -left-6 top-0 bottom-0 w-6 bg-white border-r border-gray-300 text-xs text-gray-500">
                    <!-- Ruler marks will be generated by JavaScript -->
                </div>
                
                <!-- Email Canvas -->
                <div id="emailCanvas" class="bg-white shadow-xl relative transition-all duration-300" style="width: 600px; min-height: 400px;">
                    <!-- Grid Overlay -->
                    <div id="gridOverlay" class="absolute inset-0 pointer-events-none grid-overlay opacity-20"></div>
                    
                    <!-- Canvas Content Area -->
                    <div id="canvasContent" class="relative z-10 min-h-full">
                        <!-- Main Drop Zone -->
                        <div class="drop-zone main-drop-zone min-h-full p-4" data-zone="main">
                            <!-- Template content will be rendered here -->
                            <div id="templateContent" class="space-y-4">
                                <!-- Default placeholder -->
                                <div class="text-center py-16 text-gray-400">
                                    <svg class="w-16 h-16 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                                    </svg>
                                    <p class="text-lg font-medium">Start building your email template</p>
                                    <p class="text-sm mt-1">Drag and drop components from the sidebar</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Selection Overlay -->
                    <div id="selectionOverlay" class="absolute inset-0 pointer-events-none">
                        <div id="selectionBox" class="hidden absolute border-2 border-blue-500 bg-blue-500 bg-opacity-10"></div>
                        
                        <!-- Resize Handles -->
                        <div id="resizeHandles" class="hidden absolute">
                            <div class="resize-handle resize-handle-n absolute -top-1 left-1/2 transform -translate-x-1/2 w-2 h-2 bg-blue-500 rounded-full cursor-n-resize pointer-events-auto"></div>
                            <div class="resize-handle resize-handle-s absolute -bottom-1 left-1/2 transform -translate-x-1/2 w-2 h-2 bg-blue-500 rounded-full cursor-s-resize pointer-events-auto"></div>
                            <div class="resize-handle resize-handle-e absolute top-1/2 -right-1 transform -translate-y-1/2 w-2 h-2 bg-blue-500 rounded-full cursor-e-resize pointer-events-auto"></div>
                            <div class="resize-handle resize-handle-w absolute top-1/2 -left-1 transform -translate-y-1/2 w-2 h-2 bg-blue-500 rounded-full cursor-w-resize pointer-events-auto"></div>
                            <div class="resize-handle resize-handle-ne absolute -top-1 -right-1 w-2 h-2 bg-blue-500 rounded-full cursor-ne-resize pointer-events-auto"></div>
                            <div class="resize-handle resize-handle-nw absolute -top-1 -left-1 w-2 h-2 bg-blue-500 rounded-full cursor-nw-resize pointer-events-auto"></div>
                            <div class="resize-handle resize-handle-se absolute -bottom-1 -right-1 w-2 h-2 bg-blue-500 rounded-full cursor-se-resize pointer-events-auto"></div>
                            <div class="resize-handle resize-handle-sw absolute -bottom-1 -left-1 w-2 h-2 bg-blue-500 rounded-full cursor-sw-resize pointer-events-auto"></div>
                            <div id="rotationHandle" class="absolute w-4 h-4 bg-green-500 rounded-full cursor-grab -top-6 left-1/2 -translate-x-1/2 pointer-events-auto"></div>
                        </div>
                    </div>
                </div>
                
                <!-- Canvas Information -->
                <div class="mt-4 text-center">
                    <div class="inline-flex items-center space-x-4 text-xs text-gray-500 bg-white rounded-lg px-3 py-1 shadow-sm border border-gray-200">
                        <span id="canvasSize">600 × 400</span>
                        <span>•</span>
                        <span id="selectedInfo">No selection</span>
                        <span>•</span>
                        <span id="mousePosition">0, 0</span>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Drop Zones Indicators -->
        <div id="dropIndicators" class="hidden">
            <div class="drop-indicator absolute bg-blue-500 opacity-75 pointer-events-none" style="height: 2px;"></div>
        </div>
    </div>
    
    <!-- Canvas Loading Overlay -->
    <div id="canvasLoader" class="hidden absolute inset-0 bg-white bg-opacity-75 flex items-center justify-center">
        <div class="text-center">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
            <p class="text-sm text-gray-600 mt-2">Loading template...</p>
        </div>
    </div>
</div>

<div id="contextMenu" class="hidden absolute bg-white shadow-lg rounded-md py-2 z-50">
    <a href="#" class="context-menu-item block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" data-action="edit">Edit</a>
</div>

<style>
/* Canvas specific styles */
#emailCanvas {
    box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
}

/* Device preview styles */
.device-mobile #emailCanvas {
    width: 375px;
    max-width: 375px;
}

.device-tablet #emailCanvas {
    width: 768px;
    max-width: 768px;
}

.device-desktop #emailCanvas {
    width: 1200px;
    max-width: 1200px;
}

/* Grid overlay */
.grid-overlay {
    background-image: 
        linear-gradient(rgba(59, 130, 246, 0.1) 1px, transparent 1px),
        linear-gradient(90deg, rgba(59, 130, 246, 0.1) 1px, transparent 1px);
    background-size: 20px 20px;
}

/* Drop zones */
.drop-zone {
    transition: all 0.2s ease;
    border: 2px dashed transparent;
    border-radius: 4px;
}

.drop-zone.drag-over {
    border-color: #3b82f6;
    background-color: rgba(59, 130, 246, 0.05);
}

.drop-zone:empty::before {
    content: "Drop components here";
    display: block;
    text-align: center;
    color: #9ca3af;
    font-size: 14px;
    padding: 40px 20px;
    border: 2px dashed #d1d5db;
    border-radius: 8px;
    margin: 20px;
}

/* Selection and resize handles */
.resize-handle {
    transition: all 0.15s ease;
    opacity: 0;
}

.selected-element .resize-handle {
    opacity: 1;
}

.resize-handle:hover {
    transform: scale(1.5);
}

/* Rulers */
#horizontalRuler {
    background: linear-gradient(to right, transparent 0px, transparent 9px, #d1d5db 10px, #d1d5db 11px, transparent 12px);
    background-size: 20px 100%;
}

#verticalRuler {
    background: linear-gradient(to bottom, transparent 0px, transparent 9px, #d1d5db 10px, #d1d5db 11px, transparent 12px);
    background-size: 100% 20px;
}

/* Toggle switches */
input:checked ~ div {
    background-color: #3b82f6;
}

input:checked ~ div .dot {
    transform: translateX(100%);
}

/* Zoom transitions */
#emailCanvas {
    transform-origin: center top;
}

.zoom-50 #emailCanvas {
    transform: scale(0.5);
}

.zoom-75 #emailCanvas {
    transform: scale(0.75);
}

.zoom-125 #emailCanvas {
    transform: scale(1.25);
}

.zoom-150 #emailCanvas {
    transform: scale(1.5);
}

/* Drop indicators */
.drop-indicator {
    transition: all 0.15s ease;
    border-radius: 1px;
}

/* Component highlighting */
.component-hover {
    outline: 2px solid rgba(59, 130, 246, 0.5);
    outline-offset: 2px;
}

.component-selected {
    outline: 2px solid #3b82f6;
    outline-offset: 2px;
}

/* Canvas scrollbar */
#canvasContainer::-webkit-scrollbar {
    width: 8px;
    height: 8px;
}

#canvasContainer::-webkit-scrollbar-track {
    background: #f1f1f1;
}

#canvasContainer::-webkit-scrollbar-thumb {
    background: #c1c1c1;
    border-radius: 4px;
}

#canvasContainer::-webkit-scrollbar-thumb:hover {
    background: #a8a8a8;
}

#rotationHandle {
    cursor: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M23 4v6h-6"/><path d="M1 20v-6h6"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg>') 12 12, auto;
}
</style> 